
#==========================  Modules configuration =============================
filebeat.modules:

#-------------------------------- System Module --------------------------------
- module: system
  syslog:
    enabled: true

  # Authorization logs
  auth:
    enabled: true


# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  enabled: true

  hosts: ["192.168.56.10:9200"]
  username: "filebeat_user"
  password: "${ES_PWD}"
  preset: balanced

